### ISSUE TITLE
Use thiserror instead of anyhow for error handling

### ISSUE THREAD

**Issue by ariel-miculas** [containers/ocidir-rs#15]
`thiserror` is often used in libraries, whereas `anyhow` is usually used in applications. My use case is that I want to convert from errors returned by this library into errors that PuzzleFS uses, see: https://github.com/project-machine/puzzlefs/blob/master/puzzlefs-lib/src/format/error.rs

**Comment by cgwalters** [comment]
PR in https://github.com/containers/ocidir-rs/pull/16
